name: Medievo-Utils
version: ${project.version}
main: org.elmedievo.medievoutils.MedievoUtils
authors: [BGMP, BGMM, BGem]
description: Utilidades complementarias para el plugin medieval
commands:
  restart:
    usage: /restart
    description: Restarts the server.
  cancel:
    usage: /cancel
    description: Cancels a countdown.
  fly:
    usage: /fly
    description: Enables fly mode.
  broadcast:
    usage: /broadcast
    description: Broadcasts a message,
    aliases: [br]
  head:
    usage: /head
    description: Gives you any player's head.
    aliases: [skull, ph]
  gamemode:
    usage: /gamemode
    description: Sets your gamemode.
    aliases: [gm]
  teleport:
    usage: /teleport
    description: Teleports you.
    aliases: [tp]
  message:
    usage: /message
    description: Send a private messages to other players.
    aliases: [msg, pm]
  reply:
    usage: /reply
    description: Replies to the last private message sent or received.
    aliases: [r]
  reloadscoreboard:
    usage: /reloadscoreboard
    description: Reloads the scorebaord.
    aliases: [rlscoreboard, rlscore, rlsb]
permissions:
  medievo.utils.gamemode:
    description: Permission for the gamemode command.
    default: op
  medievo.utils.teleport:
    description:  Permission for the teleport command.
    default: op
  medievo.utils.broadcast:
    description: Permission for the broadcast command.
    default: op
  medievo.utils.fly:
    description: Permission for the fly command.
    default: op
  medievo.utils.head:
    description: Permission for the heads command.
    default: op
  medievo.utils.restart:
    description: Permission for restarting the server
    default: op
  medievo.utils.cancel:
    description: Permission for cancelling a countdown.
    default: op
  medievo.utils.reloadscoreboard:
    description: Permission for reloading the scoreboard.
    default: op